import Link from 'next/link';
import { AdminShell, EmptyState, SectionHeading, StatusBadge, formatDate } from '@/components/admin/AdminShell';
import { requireAdmin } from '@/lib/auth/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function CompaniesPage({ searchParams }: { searchParams: { q?: string } }) {
  await requireAdmin(); const supabase = await createServerSupabaseClient();
  if (!supabase) return <AdminShell title="Companies" description="Browse every business and its submitted responses."><EmptyState>Unable to load companies.</EmptyState></AdminShell>;
  const query = searchParams.q?.trim() ?? '';
  let request = supabase.from('companies').select('id,name,industry,size,created_at,interviews(id,status,started_at,completed_at)').order('created_at', { ascending: false });
  if (query) request = request.ilike('name', `%${query}%`);
  const { data } = await request; const companies = data ?? [];
  return <AdminShell title="Companies" description="Open a company to review every interview question and response."><SectionHeading eyebrow="Business responses" title={`${companies.length} ${companies.length === 1 ? 'company' : 'companies'}`} action={<form method="get" className="flex gap-2"><input name="q" defaultValue={query} placeholder="Search companies" className="w-48 rounded-lg border border-black/10 bg-white px-3 py-2 text-sm" /><button className="rounded-lg bg-black px-3 py-2 text-sm text-white">Search</button></form>} />{companies.length ? <div className="overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="hidden grid-cols-[1.4fr_1fr_0.8fr_1fr] gap-4 border-b border-black/10 bg-[#fafafa] px-5 py-3 text-[10px] font-semibold uppercase tracking-wide text-subtle md:grid"><span>Company</span><span>Industry and size</span><span>Status</span><span>Submitted</span></div>{companies.map((company: any) => { const latest = (company.interviews ?? []).slice().sort((a: any, b: any) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime())[0]; return <Link key={company.id} href={`/admin/companies/${company.id}`} className="grid gap-3 border-b border-black/5 p-5 last:border-0 hover:bg-[#fafafa] md:grid-cols-[1.4fr_1fr_0.8fr_1fr] md:items-center md:gap-4"><div><p className="font-semibold">{company.name}</p><p className="mt-1 text-sm text-subtle">View responses →</p></div><p className="text-sm text-subtle">{company.industry || 'Not provided'}{company.size ? ` · ${company.size} employees` : ''}</p><div>{latest ? <StatusBadge status={latest.status} /> : <span className="text-sm text-subtle">No interview</span>}</div><p className="text-sm text-subtle">{latest ? formatDate(latest.completed_at || latest.started_at) : 'Not submitted'}</p></Link>; })}</div> : <EmptyState>{query ? 'No companies match your search.' : 'No companies recorded yet.'}</EmptyState>}</AdminShell>;
}
