import Link from 'next/link';
import { ArrowRight, ClipboardList, Clock, ShieldCheck } from 'lucide-react';

export default function LandingPage() {
  return <main className="flex min-h-screen flex-col justify-between bg-white text-black"><header className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-8"><div><p className="font-semibold">Business Discovery</p><p className="mt-1 text-xs text-subtle">A short business interview</p></div><Link href="/sign-in" className="text-sm underline underline-offset-4">Admin sign in</Link></header><section className="mx-auto my-auto w-full max-w-4xl px-6 py-14 text-center"><div className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-[#fafafa] px-3 py-1.5 text-xs text-subtle"><ClipboardList className="h-3.5 w-3.5" />Quick, private, and account-free</div><h1 className="mx-auto mt-6 max-w-3xl text-4xl font-semibold leading-tight tracking-tight sm:text-6xl">Help us understand your business.</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-subtle">Answer a few simple questions, one at a time. No password, account, or sign-in is required.</p><Link href="/discovery" className="mx-auto mt-8 inline-flex items-center gap-2 rounded-2xl bg-black px-6 py-4 text-sm font-semibold text-white">Start the interview <ArrowRight className="h-4 w-4" /></Link><div className="mt-14 grid gap-4 text-left sm:grid-cols-3"><Feature icon={<Clock className="h-4 w-4" />} title="About 10 minutes" text="A focused set of 11 questions." /><Feature icon={<ClipboardList className="h-4 w-4" />} title="One at a time" text="Clear, simple questions with room to explain." /><Feature icon={<ShieldCheck className="h-4 w-4" />} title="No account needed" text="Start immediately from any device." /></div></section><footer className="mx-auto w-full max-w-5xl border-t border-black/10 px-6 py-7 text-center text-xs text-subtle">Business Discovery</footer></main>;
}

function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) {
  return <article className="rounded-2xl border border-black/10 bg-[#fafafa] p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide">{icon}{title}</div><p className="mt-3 text-sm leading-6 text-subtle">{text}</p></article>;
}
