import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AdminShell, EmptyState, Info, SectionHeading, StatusBadge, formatDate } from '@/components/admin/AdminShell';
import { requireAdmin } from '@/lib/auth/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function AdminInterviewDetail({ params }: { params: { id: string } }) {
  await requireAdmin(); const supabase = await createServerSupabaseClient(); if (!supabase) notFound();
  const { data: interview } = await supabase.from('interviews').select('id,status,started_at,completed_at,respondent_name,respondent_role,respondent_email,respondent_phone,companies(id,name,industry,website,size)').eq('id', params.id).maybeSingle();
  if (!interview) notFound();
  const [{ data: questions }, { data: answers }] = await Promise.all([supabase.from('interview_questions').select('id,question_text,question_type,sequence_number').eq('interview_id', params.id).order('sequence_number'), supabase.from('answers').select('id,question_id,answer_text').eq('interview_id', params.id)]);
  const company = Array.isArray(interview.companies) ? interview.companies[0] : interview.companies;
  const answerMap = new Map((answers ?? []).map((answer: any) => [answer.question_id, answer]));
  return <AdminShell title="Interview detail" description="The submitted company information and complete respondent answers."><div className="space-y-8"><Link href={company?.id ? `/admin/companies/${company.id}` : '/admin/interviews'} className="text-sm underline underline-offset-4">← Back</Link><section className="rounded-2xl border border-black/10 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-subtle">{company?.name ?? 'Unknown company'}</p><h2 className="mt-1 text-2xl font-semibold">Interview record</h2></div><StatusBadge status={interview.status} /></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Started" value={formatDate(interview.started_at)} /><Info label="Submitted" value={formatDate(interview.completed_at)} /><Info label="Respondent" value={interview.respondent_name} /><Info label="Role" value={interview.respondent_role} /></div></section><section><SectionHeading eyebrow="Source of truth" title="Questions and answers" />{(questions ?? []).length ? <div className="space-y-3">{(questions ?? []).map((question: any, index: number) => { const answer = answerMap.get(question.id); return <article key={question.id} className="rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-subtle">Question {index + 1}</p><h3 className="mt-2 font-medium leading-6">{question.question_text}</h3><div className="mt-4 rounded-xl bg-[#f7f8fa] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-subtle">Answer</p><div className="mt-2 text-sm leading-6">{answer?.answer_text ? <p className="whitespace-pre-wrap break-words">{answer.answer_text}</p> : <p className="italic text-subtle">Not answered</p>}</div></div></article>; })}</div> : <EmptyState>No questions were recorded for this interview.</EmptyState>}</section></div></AdminShell>;
}
