import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AdminShell, EmptyState, Info, ReadableValue, SectionHeading, StatusBadge, formatDate, formatDuration } from '@/components/admin/AdminShell';
import { requireAdmin } from '@/lib/auth/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function AdminInterviewDetail({ params }: { params: { id: string } }) {
    await requireAdmin();
    const supabase = await createServerSupabaseClient();
    if (!supabase) notFound();
    const { data: interview } = await supabase.from('interviews').select('id,status,started_at,completed_at,last_activity_at,target_duration_seconds,respondent_name,respondent_role,respondent_email,respondent_phone,company_id,created_by,created_at,companies(id,name,industry,website,size)').eq('id', params.id).maybeSingle();
    if (!interview) notFound();
    const [{ data: questions }, { data: answers }, { data: facts }, { data: problems }, { data: recommendations }, { data: reports }, { data: logs }, { data: creator }] = await Promise.all([
        supabase.from('interview_questions').select('id,question_key,question_text,question_type,sequence_number,displayed_at,answered_at').eq('interview_id', params.id).order('sequence_number', { ascending: true }),
        supabase.from('answers').select('id,question_id,answer_text,answer_json,created_at').eq('interview_id', params.id).order('created_at', { ascending: true }),
        supabase.from('business_facts').select('id,category,key,value,source_answer_id,created_at').eq('interview_id', params.id).order('created_at', { ascending: true }),
        supabase.from('problems').select('id,title,description,frequency,severity,people_affected,time_impact_hours_per_week,financial_impact,current_solution,created_at').eq('interview_id', params.id).order('created_at', { ascending: true }),
        supabase.from('recommendations').select('id,title,type,problem_solved,evidence,why_it_matters,expected_impact,implementation_difficulty,priority,suggested_approach,risks,next_step,created_at').eq('interview_id', params.id).order('created_at', { ascending: true }),
        supabase.from('reports').select('id,executive_summary,business_snapshot,major_problems,opportunities,roadmap,raw_ai_output,created_at,updated_at').eq('interview_id', params.id).order('created_at', { ascending: false }),
        supabase.from('decision_logs').select('id,phase,objective,reason_code,state_change,confidence,model_latency_ms,token_usage,created_at').eq('interview_id', params.id).order('created_at', { ascending: true }),
        interview.created_by ? supabase.from('profiles').select('full_name,email').eq('id', interview.created_by).maybeSingle() : Promise.resolve({ data: null }),
    ]);
    const company = Array.isArray(interview.companies) ? interview.companies[0] : interview.companies;
    const answerMap = new Map<string, any[]>();
    (answers ?? []).forEach((answer: any) => answerMap.set(answer.question_id, [...(answerMap.get(answer.question_id) ?? []), answer]));
    const diagnosticFacts = (facts ?? []).filter((fact: any) => fact.category === 'diagnostic_signal');
    return <AdminShell title="Interview detail" description="Complete evidence trail for this discovery session, from respondent answers to generated intelligence.">
        <div className="space-y-8">
            <Link href="/admin/interviews" className="text-sm underline underline-offset-4">← Back to interviews</Link>
            <header className="flex flex-col gap-4 border-b border-black/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="truncate text-sm text-subtle">{company?.name ?? 'Unknown company'}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Discovery interview</h1><p className="mt-2 break-all font-mono text-[10px] text-subtle">{interview.id}</p></div><StatusBadge status={interview.status} /></header>
            <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-2xl border border-black/10 bg-white p-6"><SectionHeading eyebrow="Session record" title="Interview overview" /><div className="grid gap-5 sm:grid-cols-2"><Info label="Company" value={company?.name} /><Info label="Phase" value={interview.status === 'in_progress' ? 'Interview in progress' : interview.status} /><Info label="Started" value={formatDate(interview.started_at)} /><Info label="Completed" value={formatDate(interview.completed_at)} /><Info label="Target duration" value={interview.target_duration_seconds ? `${Math.round(interview.target_duration_seconds / 60)} minutes` : null} /><Info label="Actual duration" value={formatDuration(interview.started_at, interview.completed_at)} /><Info label="Created by" value={creator?.full_name || creator?.email || interview.created_by} /><Info label="Last activity" value={formatDate(interview.last_activity_at)} /></div></div><div className="rounded-2xl border border-black/10 bg-white p-6"><SectionHeading eyebrow="Respondent" title="Contact information" /><div className="grid gap-5 sm:grid-cols-2"><Info label="Name" value={interview.respondent_name} /><Info label="Role" value={interview.respondent_role} /><Info label="Email" value={interview.respondent_email} /><Info label="Phone" value={interview.respondent_phone} /></div></div></section>
            <section><SectionHeading eyebrow="Evidence" title={`Questions and answers · ${(questions ?? []).length}`} />{(questions ?? []).length ? <div className="space-y-3">{(questions ?? []).map((question: any, index: number) => { const responses = answerMap.get(question.id) ?? []; return <article key={question.id} className="rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><div className="flex gap-4"><span className="shrink-0 font-mono text-xs text-subtle">{String(index + 1).padStart(2, '0')}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-medium leading-6">{question.question_text}</h3><span className="rounded-full bg-[#f2f3f5] px-2 py-1 text-[10px] capitalize text-subtle">{question.question_type?.replace(/_/g, ' ')}</span></div><div className="mt-4 rounded-xl bg-[#f7f8fa] p-4"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-subtle">Answer</p>{responses.length ? responses.map((answer: any) => <div key={answer.id} className="space-y-2 text-sm">{answer.answer_text ? <p className="whitespace-pre-wrap leading-6">{answer.answer_text}</p> : answer.answer_json ? <ReadableValue value={answer.answer_json} /> : <p className="italic text-subtle">Answered without readable content</p>}<details className="pt-2 text-xs text-subtle"><summary className="cursor-pointer">View raw answer data</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap">{JSON.stringify(answer.answer_json ?? answer.answer_text, null, 2)}</pre></details></div>) : <p className="text-sm italic text-subtle">Unanswered</p>}</div></div></div></article>; })}</div> : <EmptyState>No questions recorded for this interview.</EmptyState>}</section>
            <section><SectionHeading eyebrow="Discovery data" title="Business facts" />{(facts ?? []).filter((fact: any) => fact.category !== 'diagnostic_signal').length ? <div className="grid gap-3 sm:grid-cols-2">{(facts ?? []).filter((fact: any) => fact.category !== 'diagnostic_signal').map((fact: any) => <article key={fact.id} className="rounded-2xl border border-black/10 bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-wide text-subtle">{fact.category}</p><h3 className="mt-1 font-semibold">{fact.key}</h3><div className="mt-3 text-sm"><ReadableValue value={fact.value} /></div></article>)}</div> : <EmptyState>No business facts extracted yet.</EmptyState>}</section>
            <section><SectionHeading title="Problems identified" />{(problems ?? []).length ? <div className="space-y-3">{(problems ?? []).map((problem: any) => <article key={problem.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{problem.title}</h3>{problem.severity != null && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs text-amber-700">Severity {problem.severity}/10</span>}</div>{problem.description && <p className="mt-2 text-sm leading-6 text-subtle">{problem.description}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Frequency" value={problem.frequency} /><Info label="People affected" value={problem.people_affected} /><Info label="Time impact" value={problem.time_impact_hours_per_week ? `${problem.time_impact_hours_per_week} hours/week` : null} /><Info label="Financial impact" value={problem.financial_impact} /><Info label="Current solution" value={problem.current_solution} /></div></article>)}</div> : <EmptyState>No problems recorded yet.</EmptyState>}</section>
            {diagnosticFacts.length > 0 && <section><SectionHeading title="Diagnostic signals" /><div className="flex flex-wrap gap-2">{diagnosticFacts.map((fact: any) => <span key={fact.id} className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs text-blue-700">{fact.key.replace(/_/g, ' ')}</span>)}</div></section>}
            <section><SectionHeading title="Recommendations" />{(recommendations ?? []).length ? <div className="space-y-3">{(recommendations ?? []).map((recommendation: any) => <article key={recommendation.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{recommendation.title}</h3><p className="mt-1 text-xs capitalize text-subtle">{recommendation.type}</p></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-700">{recommendation.priority || 'Priority not set'}</span><span className="rounded-full bg-[#f2f3f5] px-2.5 py-1 text-subtle">{recommendation.implementation_difficulty || 'Difficulty not set'}</span></div></div>{recommendation.problem_solved && <p className="mt-4 text-sm"><strong>Problem solved:</strong> {recommendation.problem_solved}</p>}{recommendation.evidence && <div className="mt-4 text-sm"><p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-subtle">Evidence</p><ReadableValue value={recommendation.evidence} /></div>}{recommendation.why_it_matters && <p className="mt-4 text-sm leading-6 text-subtle">{recommendation.why_it_matters}</p>}{recommendation.suggested_approach && <p className="mt-4 text-sm leading-6"><strong>Approach:</strong> {recommendation.suggested_approach}</p>}{recommendation.next_step && <p className="mt-4 text-sm"><strong>Next step:</strong> {recommendation.next_step}</p>}</article>)}</div> : <EmptyState>No recommendations generated yet.</EmptyState>}</section>
            <section><SectionHeading title="AI report" />{(reports ?? []).length ? (reports ?? []).map((report: any) => <article key={report.id} className="rounded-2xl border border-black/10 bg-white p-6"><p className="text-xs text-subtle">Created {formatDate(report.created_at)}</p><h3 className="mt-3 text-lg font-semibold">Executive summary</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{report.executive_summary || 'No executive summary available.'}</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-subtle">Business snapshot</p><ReadableValue value={report.business_snapshot} /></div><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-subtle">Roadmap</p><ReadableValue value={report.roadmap} /></div></div><details className="mt-6 border-t border-black/10 pt-4"><summary className="cursor-pointer text-sm font-medium">View raw AI output</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-[#f7f8fa] p-4 text-xs">{JSON.stringify(report.raw_ai_output, null, 2)}</pre></details></article>) : <EmptyState>No report generated yet.</EmptyState>}</section>
            {(logs ?? []).length > 0 && <section><SectionHeading title="Decision log" /><div className="rounded-2xl border border-black/10 bg-white">{(logs ?? []).map((log: any) => <div key={log.id} className="grid gap-2 border-b border-black/5 p-4 last:border-0 sm:grid-cols-[0.8fr_1fr_1fr_0.7fr]"><span className="text-xs text-subtle">{formatDate(log.created_at)}</span><span className="text-sm">{log.phase}</span><span className="text-sm">{log.objective}</span><span className="text-xs text-subtle">{log.reason_code}</span></div>)}</div></section>}
        </div>
    </AdminShell>;
}
